language: node_js
node_js:
  - "10"
install: 
  - npm install
cache:
  directories:
  - node_modules
script:
  - npm test
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master