sudo: required
services:
  - docker
language: node_js
node_js:
  - "10"
before_install: 
  # install heroku CLI 
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh 
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login --username="$HEROKU_USERNAME" --password=$(heroku auth:token) registry.heroku.com
install: 
  - npm install
cache:
  directories:
  - node_modules
script:
  - npm test
  - sh scripts/build.sh
deploy:
  provider: script
  script:
    sh scripts/deploy.sh

# after_success:
#   - sh scripts/docker_push.sh
#   - test "$TRAVIS_BRANCH" = "master" && sh scripts/heroku_deploy.sh
